export default [
    {
        id: 12,
        profession: 'Фулстек веб разработчик',
        salary: '120000 - 200000 ₽ в месяц',
        company: 'VK',
        city: 'Москва',
        badges: [{ name: 'Удаленно' }, { name: '40 часов в неделю' }],
        day_created: 1,
        count: 12,
    },
    {
        id: 13,
        profession: 'Бекенд разработчик',
        salary: '150000 - 230000 ₽ в месяц',
        company: 'VK',
        city: 'Москва',
        badges: [{ name: 'Удаленно' }],
        day_created: 2,
        count: 112,
    },
    {
        id: 14,
        profession: 'Бекенд разработчик',
        salary: '80000 - 120000 ₽ в месяц',
        company: 'Сбер',
        city: 'Москва',
        badges: [{ name: 'Удаленно' }, { name: '40 часов в неделю' }],
        day_created: 3,
        count: 302,
    },
    {
        id: 15,
        profession: 'UX/UI дизайнер',
        salary: '130000 - 240000 ₽ в месяц',
        company: 'Т-банк',
        city: 'Санкт-Петербург',
        badges: [],
        day_created: 1,
        count: 12,
    },
];
